/**
 * 48co Desktop App — Main Process
 *
 * System tray app with global hotkey that captures speech and types
 * the transcribed text into whatever application/field is currently focused.
 *
 * Architecture:
 * - Main process: tray icon, global shortcuts, keyboard simulation
 * - Renderer: floating overlay window for recording feedback
 * - Transcription: OpenAI Whisper API (primary) + Web Speech API (fallback)
 * - Typing: @nut-tree-fork/nut-js for cross-platform keyboard simulation
 */

const {
  app,
  BrowserWindow,
  Tray,
  Menu,
  globalShortcut,
  ipcMain,
  nativeImage,
  screen,
  shell,
  dialog,
  systemPreferences,
} = require('electron')
const path = require('path')
const Store = require('electron-store')
const { autoUpdater } = require('electron-updater')

// ─── Config Store ──────────────────────────────────────────────
const store = new Store({
  defaults: {
    whisperApiKey: '',
    engine: 'whisper',        // 'whisper' (Whisper API) or 'web-speech'
    language: 'en',
    pushToTalk: false,
    autoCoding: true,
    codingMode: false,
    autoSubmit: false,
    vocabulary: [],           // [{from, to}]
    replacements: [],         // [{from, to}]
    launchAtLogin: true,
    showOverlay: false,        // OFF by default — no UI on screen, just types
    typingSpeed: 0,           // 0 = instant (paste), >0 = ms between chars
    aiRewrite: false,         // AI rewrite mode — polishes dictated text
    aiRewriteMode: 'professional', // professional | casual | concise | auto
    claudeApiKey: '',         // Anthropic API key for AI rewrite
  },
})

// ─── Globals ───────────────────────────────────────────────────
let tray = null
let overlayWindow = null
let settingsWindow = null
let isRecording = false
let pttActive = false

// ─── Overlay Window (floating recording indicator) ─────────────
function createOverlayWindow() {
  const { width, height } = screen.getPrimaryDisplay().workAreaSize

  overlayWindow = new BrowserWindow({
    width: 320,
    height: 120,
    x: width - 340,
    y: height - 140,
    frame: false,
    transparent: true,
    alwaysOnTop: true,
    skipTaskbar: true,
    resizable: false,
    focusable: false,       // Critical: don't steal focus from the user's app
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  })

  overlayWindow.loadFile(path.join(__dirname, '..', 'renderer', 'overlay.html'))
  overlayWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true })

  // macOS: allow overlay to appear above fullscreen apps
  if (process.platform === 'darwin') {
    overlayWindow.setAlwaysOnTop(true, 'screen-saver', 1)
  }
}

// ─── Settings Window ───────────────────────────────────────────
function createSettingsWindow() {
  if (settingsWindow && !settingsWindow.isDestroyed()) {
    settingsWindow.focus()
    return
  }

  settingsWindow = new BrowserWindow({
    width: 480,
    height: 700,
    frame: true,
    resizable: false,
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  })

  settingsWindow.loadFile(path.join(__dirname, '..', 'renderer', 'settings.html'))
  settingsWindow.once('ready-to-show', () => settingsWindow.show())
  settingsWindow.on('closed', () => { settingsWindow = null })
}

// ─── System Tray ───────────────────────────────────────────────
function createTray() {
  // Create a simple tray icon (16x16 template image)
  // Tray icon — prefer PNG (generated by build), fall back to SVG
  const fs = require('fs')
  const pngPath = path.join(__dirname, '..', 'assets', 'tray-icon.png')
  const svgPath = path.join(__dirname, '..', 'assets', 'tray-icon.svg')
  const iconPath = fs.existsSync(pngPath) ? pngPath : svgPath
  let trayIcon
  try {
    trayIcon = nativeImage.createFromPath(iconPath)
    if (process.platform === 'darwin') {
      trayIcon = trayIcon.resize({ width: 16, height: 16 })
      trayIcon.setTemplateImage(true)
    }
  } catch {
    // Fallback: create a simple colored square icon
    trayIcon = nativeImage.createEmpty()
  }

  tray = new Tray(trayIcon)
  tray.setToolTip('48co — Voice to Text')

  updateTrayMenu()

  tray.on('click', () => {
    toggleRecording()
  })
}

function updateTrayMenu() {
  const contextMenu = Menu.buildFromTemplate([
    {
      label: isRecording ? '■ Stop Recording' : '● Start Recording',
      click: () => toggleRecording(),
    },
    { type: 'separator' },
    {
      label: 'Settings',
      click: () => createSettingsWindow(),
    },
    {
      label: `Language: ${store.get('language', 'en').toUpperCase()}`,
      enabled: false,
    },
    {
      label: `Engine: ${store.get('engine', 'whisper') === 'whisper' ? 'Whisper API' : 'Web Speech'}`,
      enabled: false,
    },
    { type: 'separator' },
    {
      label: 'Launch at Login',
      type: 'checkbox',
      checked: store.get('launchAtLogin'),
      click: (item) => {
        store.set('launchAtLogin', item.checked)
        app.setLoginItemSettings({ openAtLogin: item.checked })
      },
    },
    {
      label: 'Check for Updates',
      click: () => autoUpdater.checkForUpdatesAndNotify(),
    },
    { type: 'separator' },
    {
      label: 'Quit 48co',
      click: () => app.quit(),
    },
  ])

  tray.setContextMenu(contextMenu)
}

// ─── Recording Control ─────────────────────────────────────────
async function toggleRecording() {
  if (isRecording) {
    await stopRecording()
  } else {
    await startRecording()
  }
}

async function startRecording() {
  if (isRecording) return

  // Check API key BEFORE recording — don't waste user's time
  const engine = store.get('engine', 'whisper')
  if (engine === 'whisper' && !store.get('whisperApiKey')) {
    dialog.showMessageBox({
      type: 'warning',
      title: '48co — API Key Needed',
      message: 'You need an OpenAI API key for voice transcription.',
      detail: 'Right-click the tray icon → Settings → enter your API key.\n\nGet one at: platform.openai.com/api-keys\nCosts about $0.006 per minute of speech.',
      buttons: ['Open Settings', 'OK'],
    }).then(({ response }) => {
      if (response === 0) createSettingsWindow()
    })
    return
  }

  isRecording = true
  updateTrayMenu()

  // Tell renderer to start capturing audio (overlay handles mic access)
  if (overlayWindow) {
    overlayWindow.webContents.send('start-recording', {
      engine: store.get('engine'),
      language: store.get('language'),
      whisperApiKey: store.get('whisperApiKey'),
    })
    overlayWindow.webContents.send('recording-state', { status: 'recording' })

    // Only show overlay if user wants it — default is OFF (zero UI)
    if (store.get('showOverlay')) {
      overlayWindow.showInactive()
    }
  }
}

async function stopRecording() {
  if (!isRecording) return
  isRecording = false

  updateTrayMenu()

  // Tell renderer to stop and transcribe
  if (overlayWindow) {
    overlayWindow.webContents.send('stop-recording')
    overlayWindow.webContents.send('recording-state', { status: 'processing' })
  }
}

// ─── Keyboard Simulation (type into focused app) ──────────────
// Uses nut-tree for keyboard simulation. If nut-tree isn't available,
// falls back to clipboard copy + user notification.
let nutTree = null
try {
  nutTree = require('@nut-tree-fork/nut-js')
} catch {
  console.warn('[48co] @nut-tree-fork/nut-js not available — will use clipboard fallback')
}

async function typeText(text) {
  const { clipboard } = require('electron')

  // Hide overlay BEFORE typing so it doesn't interfere with focus
  if (overlayWindow && overlayWindow.isVisible()) {
    overlayWindow.hide()
  }

  // Give the user's app a moment to regain focus
  await new Promise(r => setTimeout(r, 150))

  // Method 1: nut-tree keyboard simulation (preferred)
  if (nutTree) {
    try {
      const { keyboard, Key } = nutTree
      const speed = store.get('typingSpeed', 0)

      if (speed === 0) {
        // Instant mode: clipboard paste (fastest, most reliable)
        const originalClipboard = clipboard.readText()
        clipboard.writeText(text)
        await new Promise(r => setTimeout(r, 100))

        if (process.platform === 'darwin') {
          await keyboard.pressKey(Key.LeftSuper)
          await keyboard.pressKey(Key.V)
          await keyboard.releaseKey(Key.V)
          await keyboard.releaseKey(Key.LeftSuper)
        } else {
          await keyboard.pressKey(Key.LeftControl)
          await keyboard.pressKey(Key.V)
          await keyboard.releaseKey(Key.V)
          await keyboard.releaseKey(Key.LeftControl)
        }

        setTimeout(() => {
          try { clipboard.writeText(originalClipboard) } catch {}
        }, 500)
      } else {
        await keyboard.type(text)
      }

      console.log('[48co] Typed', text.length, 'chars into focused app')
      return true
    } catch (err) {
      console.error('[48co] nut-tree failed:', err.message)
      // Fall through to clipboard fallback
    }
  }

  // Method 2: Clipboard fallback (always works, but user needs to Ctrl+V)
  try {
    clipboard.writeText(text)
    tray?.setToolTip('48co — Text copied! Press Ctrl+V to paste')
    setTimeout(() => tray?.setToolTip('48co — Voice to Text'), 5000)
    console.log('[48co] Copied', text.length, 'chars to clipboard (fallback)')
    return true
  } catch (clipErr) {
    console.error('[48co] Clipboard fallback failed:', clipErr.message)
    return false
  }
}

// ─── Text Processing (same pipeline as extension) ──────────────
function postProcess(text, settings) {
  let result = text

  // Punctuation substitutions
  const PUNCTUATION_MAP = [
    [/\b(full stop|period)\b/gi, '.'],
    [/\bcomma\b/gi, ','],
    [/\b(question mark)\b/gi, '?'],
    [/\b(exclamation mark|exclamation point)\b/gi, '!'],
    [/\bsemicolon\b/gi, ';'],
    [/\bcolon\b/gi, ':'],
    [/\bellipsis\b/gi, '...'],
    [/\bdash\b/gi, ' — '],
    [/\bhyphen\b/gi, '-'],
    [/\b(new line|newline)\b/gi, '\n'],
    [/\b(new paragraph)\b/gi, '\n\n'],
    [/\btab\b/gi, '\t'],
    [/\b(open parenthesis|open paren|left paren)\b/gi, '('],
    [/\b(close parenthesis|close paren|right paren)\b/gi, ')'],
    [/\b(open bracket|left bracket)\b/gi, '['],
    [/\b(close bracket|right bracket)\b/gi, ']'],
    [/\b(open brace|left brace|open curly)\b/gi, '{'],
    [/\b(close brace|right brace|close curly)\b/gi, '}'],
    [/\b(open quote|begin quote)\b/gi, '"'],
    [/\b(close quote|end quote|unquote)\b/gi, '"'],
    [/\bsingle quote\b/gi, "'"],
    [/\b(at sign|at symbol)\b/gi, '@'],
    [/\b(hash sign|hashtag|pound sign)\b/gi, '#'],
    [/\b(dollar sign)\b/gi, '$'],
    [/\b(percent sign|percentage)\b/gi, '%'],
    [/\b(ampersand)\b/gi, '&'],
    [/\b(asterisk|star)\b/gi, '*'],
    [/\bforward slash\b/gi, '/'],
    [/\bbackslash\b/gi, '\\'],
    [/\b(pipe|vertical bar)\b/gi, '|'],
    [/\b(underscore)\b/gi, '_'],
    [/\b(equals sign)\b/gi, '='],
    [/\b(plus sign)\b/gi, '+'],
    [/\b(less than|left angle)\b/gi, '<'],
    [/\b(greater than|right angle)\b/gi, '>'],
    [/\btilde\b/gi, '~'],
    [/\b(thumbs up emoji|thumbsup emoji)\b/gi, '👍'],
    [/\b(thumbs down emoji)\b/gi, '👎'],
    [/\b(smiley face|smiley emoji|smile emoji)\b/gi, '😊'],
    [/\b(heart emoji)\b/gi, '❤️'],
    [/\b(fire emoji)\b/gi, '🔥'],
    [/\b(check mark emoji|checkmark emoji)\b/gi, '✅'],
    [/\b(cross mark emoji|x emoji)\b/gi, '❌'],
    [/\b(warning emoji)\b/gi, '⚠️'],
    [/\b(rocket emoji)\b/gi, '🚀'],
    [/\b(thinking emoji)\b/gi, '🤔'],
    [/\b(clap emoji)\b/gi, '👏'],
    [/\b(laughing emoji|lol emoji)\b/gi, '😂'],
    [/\b(crying emoji|sad emoji)\b/gi, '😢'],
    [/\b(wave emoji)\b/gi, '👋'],
    [/\b(party emoji)\b/gi, '🎉'],
    [/\b(eyes emoji)\b/gi, '👀'],
    [/\b(100 emoji)\b/gi, '💯'],
    [/\b(bug emoji)\b/gi, '🐛'],
  ]

  for (const [pattern, replacement] of PUNCTUATION_MAP) {
    result = result.replace(pattern, replacement)
  }

  // Custom vocabulary
  if (settings.vocabulary && settings.vocabulary.length > 0) {
    for (const { from, to } of settings.vocabulary) {
      if (from && to) {
        const escaped = from.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
        result = result.replace(new RegExp('\\b' + escaped + '\\b', 'gi'), to)
      }
    }
  }

  // Custom text replacements
  if (settings.replacements && settings.replacements.length > 0) {
    for (const { from, to } of settings.replacements) {
      if (from && to) {
        result = result.replaceAll(from, to)
      }
    }
  }

  // Clean up punctuation spacing
  result = result.replace(/\s+([.,;:!?)\]}])/g, '$1')
  result = result.replace(/([.,;:!?])([A-Za-z])/g, '$1 $2')

  // Auto-capitalize
  result = result.replace(/^(\s*)([a-z])/, (_, ws, ch) => ws + ch.toUpperCase())
  result = result.replace(/([.!?]\s+)([a-z])/g, (_, punct, ch) => punct + ch.toUpperCase())
  result = result.replace(/(\n\s*)([a-z])/g, (_, nl, ch) => nl + ch.toUpperCase())

  // Clean up whitespace
  result = result.replace(/ {2,}/g, ' ')

  return result.trim()
}

// Voice commands
const VOICE_COMMANDS = [
  { triggers: ['refactor this'], output: 'Refactor the following code. Identify inefficiencies, simplify logic, and rewrite it cleanly:\n\n' },
  { triggers: ['explain this'], output: 'Explain what the following code does, step by step:\n\n' },
  { triggers: ['debug this'], output: 'Debug the following code. Find errors, explain them, and provide a fix:\n\n' },
  { triggers: ['fix this'], output: 'Fix the following code. Identify the bug and provide the corrected version:\n\n' },
  { triggers: ['test this'], output: 'Write comprehensive tests for the following code:\n\n' },
  { triggers: ['optimize this'], output: 'Optimize the following code for performance:\n\n' },
]

function matchCommand(text) {
  const lower = text.toLowerCase().trim()
  for (const cmd of VOICE_COMMANDS) {
    for (const trigger of cmd.triggers) {
      if (lower.includes(trigger)) return cmd
    }
  }
  return null
}

// Auto coding mode
const CODING_KEYWORDS = [
  'function', 'class', 'import', 'export', 'const', 'let', 'var',
  'loop', 'array', 'object', 'return', 'async', 'await', 'def',
  'interface', 'struct', 'enum', 'module', 'require', 'extends',
  'constructor', 'prototype', 'promise', 'component', 'useState',
  'useEffect', 'middleware', 'endpoint', 'callback',
]

function isCodingContent(text) {
  const lower = text.toLowerCase()
  return CODING_KEYWORDS.some(kw => lower.includes(kw))
}

function detectLang(text) {
  const l = text.toLowerCase()
  if (l.includes('python') || l.includes('def ')) return 'python'
  if (l.includes('rust') || l.includes('fn ')) return 'rust'
  if (l.includes('go ') || l.includes('goroutine')) return 'go'
  if (l.includes('typescript')) return 'typescript'
  if (l.includes('bash') || l.includes('terminal')) return 'bash'
  if (l.includes('sql') || l.includes('query')) return 'sql'
  if (l.includes('html') || l.includes('div ')) return 'html'
  if (l.includes('css') || l.includes('flexbox')) return 'css'
  return 'javascript'
}

function wrapCode(text) {
  return '```' + detectLang(text) + '\n' + text + '\n```'
}

// ─── AI Rewrite Mode (Claude API) ─────────────────────────────
// Takes rough dictated text and rewrites it into polished output.
// The mode changes based on context (email=professional, slack=casual, code=technical).

async function rewriteWithAI(text, settings) {
  const apiKey = settings.claudeApiKey
  if (!apiKey) return text

  const mode = settings.aiRewriteMode || 'professional'
  const appContext = detectAppContext()

  const systemPrompts = {
    professional: 'You are a writing assistant. Rewrite the user\'s dictated text into clean, professional prose. Fix grammar, remove filler words (um, uh, like, you know), improve clarity. Keep the original meaning and tone. Do NOT add information the user didn\'t say. Return ONLY the rewritten text, nothing else.',
    casual: 'You are a writing assistant. Clean up the user\'s dictated text into natural, casual writing. Fix obvious errors but keep the conversational tone. Remove filler words. Return ONLY the cleaned text.',
    concise: 'You are a writing assistant. Rewrite the user\'s dictated text to be as concise as possible. Remove all filler, redundancy, and unnecessary words. Make every word count. Return ONLY the rewritten text.',
    email: 'You are a writing assistant. Rewrite this dictated text as a professional email. Add appropriate greeting and sign-off if not present. Fix grammar and tone. Return ONLY the email text.',
    slack: 'You are a writing assistant. Clean up this dictated text for a Slack message. Keep it casual and brief. Use line breaks for readability. Return ONLY the message text.',
    code: 'You are a coding assistant. The user dictated instructions about code. Convert their spoken description into a clear, well-formatted technical request or code comment. Return ONLY the formatted text.',
  }

  // Auto-select mode based on detected app context
  let activeMode = mode
  if (appContext === 'email') activeMode = 'email'
  else if (appContext === 'slack' || appContext === 'discord') activeMode = 'slack'
  else if (appContext === 'code') activeMode = 'code'

  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), 8000) // 8s max

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 1024,
        system: systemPrompts[activeMode] || systemPrompts.professional,
        messages: [{ role: 'user', content: text }],
      }),
      signal: controller.signal,
    })

    clearTimeout(timeout)

    if (!response.ok) {
      const err = await response.text().catch(() => '')
      if (response.status === 401) throw new Error('Invalid Claude API key')
      throw new Error(`Claude API error (${response.status}): ${err}`)
    }

    const data = await response.json()
    const rewritten = data.content?.[0]?.text?.trim()

    // Safety: if AI returns empty or way too different, use original
    if (!rewritten || rewritten.length < text.length * 0.2) {
      return text
    }

    return rewritten
  } catch (err) {
    clearTimeout(timeout)
    if (err.name === 'AbortError') {
      console.warn('[48co] AI rewrite timed out (8s), using original text')
      return text
    }
    throw err
  }
}

// ─── App Context Detection ────────────────────────────────────
// Detects which app is currently focused to auto-adjust AI rewrite mode.
// Returns: 'email' | 'slack' | 'discord' | 'code' | 'terminal' | 'general'

function detectAppContext() {
  try {
    // Try to detect focused window title/process
    // This works cross-platform via BrowserWindow.getFocusedWindow fallback
    const focused = BrowserWindow.getFocusedWindow()
    const title = focused?.getTitle()?.toLowerCase() || ''

    // Check window title for app hints
    if (title.includes('gmail') || title.includes('outlook') || title.includes('mail') || title.includes('thunderbird')) return 'email'
    if (title.includes('slack')) return 'slack'
    if (title.includes('discord')) return 'discord'
    if (title.includes('vs code') || title.includes('visual studio') || title.includes('intellij') || title.includes('webstorm') || title.includes('sublime') || title.includes('vim') || title.includes('neovim')) return 'code'
    if (title.includes('terminal') || title.includes('iterm') || title.includes('powershell') || title.includes('cmd') || title.includes('warp')) return 'terminal'
    if (title.includes('notion') || title.includes('google docs') || title.includes('word')) return 'general'

    return 'general'
  } catch {
    return 'general'
  }
}

// ─── IPC Handlers ──────────────────────────────────────────────
ipcMain.handle('get-settings', () => {
  return store.store
})

ipcMain.handle('set-setting', (_, key, value) => {
  store.set(key, value)
  return true
})

ipcMain.handle('get-setting', (_, key) => {
  return store.get(key)
})

// Transcription complete — process and type
ipcMain.on('transcription-ready', async (_, text) => {
  if (!text || !text.trim()) {
    isRecording = false
    updateTrayMenu()
    if (overlayWindow) {
      overlayWindow.webContents.send('recording-state', { status: 'idle' })
      overlayWindow.hide()
    }
    return
  }

  const settings = store.store

  // Check voice commands
  const cmd = matchCommand(text)
  let output

  if (cmd) {
    output = cmd.output
  } else {
    output = postProcess(text, settings)
  }

  // Auto coding mode
  if (settings.codingMode || (settings.autoCoding && isCodingContent(output))) {
    output = wrapCode(output)
  }

  // AI Rewrite Mode — the killer feature
  if (settings.aiRewrite && settings.claudeApiKey && !cmd) {
    if (overlayWindow) {
      overlayWindow.webContents.send('recording-state', { status: 'rewriting', text: output })
    }
    try {
      output = await rewriteWithAI(output, settings)
    } catch (err) {
      console.error('[48co] AI rewrite failed, using original:', err.message)
      // Fall through with original text — never lose the user's words
    }
  }

  // Show typing state
  if (overlayWindow) {
    overlayWindow.webContents.send('recording-state', { status: 'typing', text: output })
  }

  // Type into the focused application
  const success = await typeText(output)

  // Show done state
  if (overlayWindow) {
    overlayWindow.webContents.send('recording-state', {
      status: 'done',
      success,
      text: output.substring(0, 80) + (output.length > 80 ? '...' : ''),
    })

    // Hide overlay after 1.5s
    setTimeout(() => {
      if (overlayWindow && !isRecording) {
        overlayWindow.webContents.send('recording-state', { status: 'idle' })
        overlayWindow.hide()
      }
    }, 1500)
  }

  isRecording = false
  updateTrayMenu()
})

// Transcription error
ipcMain.on('transcription-error', (_, error) => {
  console.error('Transcription error:', error)
  isRecording = false
  updateTrayMenu()

  if (overlayWindow) {
    overlayWindow.webContents.send('recording-state', {
      status: 'error',
      message: error,
    })
    setTimeout(() => {
      if (overlayWindow) {
        overlayWindow.webContents.send('recording-state', { status: 'idle' })
        overlayWindow.hide()
      }
    }, 3000)
  }
})

// ─── macOS Accessibility Permission Check ──────────────────────
async function checkAccessibilityPermission() {
  if (process.platform !== 'darwin') return true

  const trusted = systemPreferences.isTrustedAccessibilityClient(false)
  if (!trusted) {
    const { response } = await dialog.showMessageBox({
      type: 'warning',
      title: '48co — Accessibility Permission Required',
      message: '48co needs accessibility permission to type text into other applications.',
      detail: 'Click "Open System Preferences" to grant permission, then restart 48co.',
      buttons: ['Open System Preferences', 'Later'],
      defaultId: 0,
    })

    if (response === 0) {
      systemPreferences.isTrustedAccessibilityClient(true) // triggers the permission prompt
      shell.openExternal('x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility')
    }
    return false
  }
  return true
}

// ─── App Lifecycle ─────────────────────────────────────────────
app.whenReady().then(async () => {
  // Check macOS accessibility permission
  await checkAccessibilityPermission()

  // Create tray and overlay
  createTray()
  createOverlayWindow()

  // Register global shortcut: Ctrl+Shift+Space (Cmd+Shift+Space on Mac)
  const shortcut = process.platform === 'darwin' ? 'CommandOrControl+Shift+Space' : 'Ctrl+Shift+Space'

  const registered = globalShortcut.register(shortcut, () => {
    toggleRecording()
  })

  if (!registered) {
    console.error('Failed to register global shortcut:', shortcut)
  }

  // Mouse wheel click listener (global)
  // Electron doesn't have a native global mouse listener, so we use the
  // overlay window + a transparent full-screen input catcher for mouse events.
  // For now, users can configure hotkeys in settings.
  // TODO: Add iohook or similar for true global mouse button detection

  // Auto-update check
  if (app.isPackaged) {
    autoUpdater.checkForUpdatesAndNotify()
  }

  // Set login item
  app.setLoginItemSettings({
    openAtLogin: store.get('launchAtLogin', true),
  })

  // Microphone permission check (macOS)
  if (process.platform === 'darwin') {
    const micStatus = systemPreferences.getMediaAccessStatus('microphone')
    if (micStatus !== 'granted') {
      await systemPreferences.askForMediaAccess('microphone')
    }
  }
})

// Don't quit when all windows are closed (we're a tray app)
app.on('window-all-closed', (e) => {
  e.preventDefault()
})

// Clean up on quit
app.on('will-quit', () => {
  globalShortcut.unregisterAll()
})

// Prevent multiple instances
const gotLock = app.requestSingleInstanceLock()
if (!gotLock) {
  app.quit()
} else {
  app.on('second-instance', () => {
    // If user tries to open another instance, show settings
    createSettingsWindow()
  })
}
